# Generated by Django 3.1 on 2021-03-08 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileAddresses',
        ),
    ]
