# Generated by Django 3.1 on 2021-03-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_userprofileaddresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_library_account',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
