# Generated by Django 3.1 on 2021-03-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_is_library_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_library_account',
        ),
    ]
