# Generated by Django 3.1 on 2021-03-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userprofile_is_library_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_library_account',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
